<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container33vxZTO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container33vxZTO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container33vxZTO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container33vxZTO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container33vxZTO\App_KernelDevDebugContainer([
    'container.build_hash' => '33vxZTO',
    'container.build_id' => '721fdd4f',
    'container.build_time' => 1637136606,
], __DIR__.\DIRECTORY_SEPARATOR.'Container33vxZTO');
