<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQMkWok3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQMkWok3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQMkWok3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQMkWok3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQMkWok3\App_KernelDevDebugContainer([
    'container.build_hash' => 'QMkWok3',
    'container.build_id' => 'e1c6bb28',
    'container.build_time' => 1638182187,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQMkWok3');
