<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXGUN2JK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXGUN2JK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXGUN2JK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXGUN2JK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXGUN2JK\App_KernelDevDebugContainer([
    'container.build_hash' => 'XGUN2JK',
    'container.build_id' => '0781f85c',
    'container.build_time' => 1637142189,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXGUN2JK');
